apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "all-reduce-perf-nccl-without-ib"
spec:
  checkType: "slurmJob"
  name: "all-reduce-perf-nccl-without-ib"
  dependsOn: [ "create-user-soperatorchecks", "wait-for-topology" ]
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  schedule: "0 */4 * * *" # Every 4 hours
  suspend: false
  runAfterCreation: true
  slurmJobSpec:
    sbatchScript: |
{{ .Files.Get "scripts/all-reduce-perf-nccl-without-ib.sh" | indent 6 }}
    eachWorkerJobs: true
    jobContainer:
      image: {{ .Values.images.slurmJob | quote }}
      env:
{{ toYaml .Values.jobContainer.env | indent 8 }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
    mungeContainer:
      image: {{ .Values.images.munge | quote }}
  reactions:
    setCondition: true
    drainSlurmNode: true
