apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "soperator-outputs-logs-cleaner"
spec:
  checkType: "k8sJob"
  schedule: "0 17 * * *" # 1 time a day at 17:00 UTC
  name: "soperator-outputs-logs-cleaner"
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  suspend: false
  runAfterCreation: false
  k8sJobSpec:
    jobContainer:
      command:
        - bash
        - -c
        - |
{{ .Files.Get "scripts/soperator-outputs-logs-cleaner.sh" | indent 10 }}
      image: {{ .Values.images.k8sJob | quote }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
